name: documentation
version: "1.0.0"
type: prompt
description: "技术文档编写专家 - 提供专业、友好、简洁的文档"

triggers:
  keywords:
    - "文档"
    - "documentation"
    - "docs"
    - "README"
    - "API文档"
  context:
    - file_pattern: "*.md"
      action: "edit"

llm:
  model: qwen-max
  temperature: 0.7
  max_tokens: 2000

inputs:
  - name: content_type
    type: string
    required: false
    description: "文档类型（API/README/Tutorial等）"
  - name: user_message
    type: string
    required: true
    description: "用户需求描述"

outputs:
  - name: document
    type: string
    description: "生成的文档内容"

scope:
  level: file
  auto_load: false
